### ISSUE TITLE
Style ui files with css/qss as much as possible

### ISSUE THREAD

**Issue by cpeck-rmvd** [starlingcode/viaflash#4]
Right now the only style sheets to describe the UI are highly minimal. Would smash down your LOC to implement meaningful names, id's, classes in style sheets, whereas it looks like the .py files right now determine almost all of that.

Not sure how much of this is boilerplate code.

Offering suggestions if welcome.

**Comment by liquidcitymotors** [comment]
Please see https://github.com/starlingcode/viaflash/issues/3, the ui_*.py files are generated from the .ui files. It would be a huge amount of work to do away with the QtDesigner workflow and define the interface programmatically. The style sheet is minimal because the functionality of the app is still being developed and I'm largely not worrying about styling something that likely won't get used by anyone other than me and maybe one or two others.
